name: CI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Docker Compose app Up 
        run: docker compose -f 'app/docker-compose.yml' up -d --build 'app' 

      - name: Run tests
        run: docker compose -f 'app/docker-compose.yml' up -d --build 'test' 
